### ISSUE TITLE
Add convolutional Layer

### ISSUE THREAD

**Issue by Hitomamacs** [ZIGTinyBook/Z-Ant#88]
### Feature Description

Add convolutional layer and use it to build a model for mnist training with 2D data (Both for training and inference)

### Problem Statement

Right now we feed data only in a linear way

### Suggested Solution

2D Convolutional Layer

### Additional Context

Look also at MaxPooling, we will have a separate issue for it

<sub><a href="https://huly.app/guest/thetinybook?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzMxY2Q0N2U3Y2M1YTc4NTQyYWEyOTciLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctZ2l0aHViZmxhbWFuLXRoZXRpbnlib29rLTY3MGU4NzBiLWRjYzkyNjFmMDItMTMxM2JkIn0._sVgy0op-nh4NRCQY_dd1UM8CMBTmPy1zx4xUL9H8js">Huly&reg;: <b>X_PI-118</b></a></sub>

**Comment by MirkoCalvi** [comment]
Continued by @Hitomamacs in branch "convolutional"
