### ISSUE TITLE
Implemet MaxPooling Layer

### ISSUE THREAD

**Issue by Hitomamacs** [ZIGTinyBook/Z-Ant#89]
### Feature Description

Implement MaxPooling Layer both for training and iference

### Problem Statement

For a correct CNN mOdel we need Max Pooling

### Suggested Solution

Should be easy implement it

### Additional Context

Issue correlated wit CNN

<sub><a href="https://huly.app/guest/thetinybook?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzMxY2Q4N2U3Y2M1YTc4NTQyYWEyYjgiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctZ2l0aHViZmxhbWFuLXRoZXRpbnlib29rLTY3MGU4NzBiLWRjYzkyNjFmMDItMTMxM2JkIn0.04-8ltZM_WApLZNxPHMcUIEBs5H3rPFtbIGDa2rB--g">Huly&reg;: <b>X_PI-119</b></a></sub>

**Comment by MirkoCalvi** [comment]
Mooved into "convolutional" branch from [this](https://github.com/ZIGTinyBook/Z-Ant/commit/d10001f2e458daed7ea02adfcd9a68e8c90d0d74) commmit.
